### ISSUE TITLE
Cannot use js-spec-chai 0.1.2-0 with js.spec-1.0.0-10

### ISSUE THREAD

**Issue by mattbishop** [arichiardi/js-spec-chai#1]
I get this: 

Error: Cannot coerce StringData to spec
      at s (node_modules/js-spec-chai/node_modules/js.spec/dist/js.spec.js:1:2803)
      at l (node_modules/js-spec-chai/node_modules/js.spec/dist/js.spec.js:1:2618)
      at Object.t.valid (node_modules/js-spec-chai/node_modules/js.spec/dist/js.spec.js:1:3974)
      at Proxy.<anonymous> (node_modules/js-spec-chai/src/index.ts:41:19)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.it (test/specs.test.ts:41:29)

**Comment by arichiardi** [comment]
I guess I need to bump, will investigate this.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mattbishop** [comment]
I'd like to know why you have to rev your version too. Is there a change to js.spec that would make it possible to not have to rev your lib?

**Comment by arichiardi** [comment]
My wild guess is that I missed some symbol when avoiding mangling in js.spec. Some code path was untested maybe.

**Comment by arichiardi** [comment]
No, it was just a problem with `js.spec`, I pushed a new version of `js.spec` and a quick fix for a test + new version for `js-spec-chai` that fixes the (usual) problem.
